# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c756d7ae29f3a8bec7de461208b3d1a814fdfa50676bf1523ce969ffe055ea38649cd1c2382adab0d2722a19d6599342481a4316a9db63c953aafac609997e68

test:
  secret_key_base: c4288bf7e5409ffc84f8602bad5220923dc1b8de6235b1dfaaba3a9659190cd44cb17d882db68e162ee48361b13b993ebf58bdc72e6c3d014545f34f62af6462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
